
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Frame6 extends javax.swing.JFrame {
    private int saldo;
    int bal;
    int s;
    int tab;
    int t;
    
    /**
     * Creates new form Frame6
     */
    public Frame6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputansetor = new javax.swing.JTextField();
        nilai = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ya = new javax.swing.JButton();
        keluar1 = new javax.swing.JButton();
        buttonyasetor = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        penarikan = new javax.swing.JTextField();
        oktarik = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        jLabel2.setText("BNI SYARIAH CABANG NGAWI");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 10, 340, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Jln. Yos Sudarso No.17 B, Kec.Ngawi, Kab. Ngawi, Jawa Timur");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 30, 380, 20);

        jLabel1.setFont(new java.awt.Font("Century751 No2 BT", 2, 14)); // NOI18N
        jLabel1.setText("BNI Syariah Memberikan Yang Terbaik Sesuai Kaidah");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 50, 350, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("PENYETORAN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 220, 110, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Jumlah Saldo Anda Saat Ini :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 330, 180, 30);
        getContentPane().add(inputansetor);
        inputansetor.setBounds(260, 250, 200, 30);
        getContentPane().add(nilai);
        nilai.setBounds(270, 340, 180, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Apakah Anda ingin melakukan Transaksi Lainnya ?");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 370, 310, 30);

        ya.setBackground(new java.awt.Color(255, 0, 204));
        ya.setText("YA");
        ya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaActionPerformed(evt);
            }
        });
        getContentPane().add(ya);
        ya.setBounds(160, 410, 170, 30);

        keluar1.setBackground(new java.awt.Color(255, 0, 204));
        keluar1.setText("TIDAK");
        keluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluar1ActionPerformed(evt);
            }
        });
        getContentPane().add(keluar1);
        keluar1.setBounds(160, 450, 170, 30);

        buttonyasetor.setText("YA");
        buttonyasetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonyasetorActionPerformed(evt);
            }
        });
        getContentPane().add(buttonyasetor);
        buttonyasetor.setBounds(220, 290, 45, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("PENARIKAN");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(200, 80, 90, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Masukkan Jumlah Nominal");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 130, 180, 30);
        getContentPane().add(penarikan);
        penarikan.setBounds(260, 130, 200, 30);

        oktarik.setText("OK");
        oktarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oktarikActionPerformed(evt);
            }
        });
        getContentPane().add(oktarik);
        oktarik.setBounds(220, 170, 47, 23);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Masukkan Jumlah Nominal");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 250, 180, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon("K:\\Background\\1332463569169212797vactor flower.png")); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-260, -10, 790, 510);

        setBounds(0, 0, 514, 536);
    }// </editor-fold>//GEN-END:initComponents

    private void yaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaActionPerformed
         new Frame2().setVisible(true);     
         dispose();// TODO add your handling code here:
    }//GEN-LAST:event_yaActionPerformed

    private void keluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluar1ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_keluar1ActionPerformed

    private void buttonyasetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonyasetorActionPerformed
      
        String setor = inputansetor.getText();
        String saldolast = nilai.getText();
        nilai.setText(""+saldolast);
        int jmlsetor = Integer.parseInt(setor);
        int lastsaldo = Integer.parseInt(saldolast);
        int total = lastsaldo+jmlsetor;
        nilai.setText(""+total);
        
        if (s%100!=0)
            JOptionPane.showMessageDialog(null,
                    "Mesin ATM BRI tidak menerima uang koin \nSilahkan ulangi kembali!",
                    "Transaksi Gagal", 0);
        else if (s<50000)
            JOptionPane.showMessageDialog(null,
                    "Besaran minimal setor tunai adalah Rp. 50000, 00", "ERROR",0);
        else if (s>=50000){
            saldo = bal+s;
            JOptionPane.showMessageDialog(null, 
                    "Saldo Anda saat ini sebesar :" + saldo);
            }  
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonyasetorActionPerformed

    private void oktarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oktarikActionPerformed
        String tarikan = penarikan.getText();
        int saldo = 150000;
        int jmltarik = Integer.parseInt(tarikan);
        int total = saldo-jmltarik;
        nilai.setText(""+total);
        
        if (t%100!=0)
            JOptionPane.showMessageDialog(null, "Mesin ATM ini tidak menerima uang koin \nSilahkan ulangi lagi", "Transaksi Gagal", 0);
        else{
            if(t>tab)
                JOptionPane.showMessageDialog(null,"Saldo Anda tidak mencukupi \nSilahkan lakukan penyetoran","Transaksi Gagal", 0);
            else if(t<50000)
                JOptionPane.showMessageDialog(null,
                    "Besaran minimal pengambilan tunai adalah Rp. 50000, 00", "Transaksi Gagal",0);
            else{
                saldo = tab-t;
                JOptionPane.showMessageDialog(null,"Saldo Anda saat ini sebesar :"+saldo);
                if(tab<=50000)
                    JOptionPane.showMessageDialog(null,"Saldo minimal Rp. 50000,00 Segera lakukan penyetoran untuk menghindari penutupan akun.","CAUTION",2);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_oktarikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonyasetor;
    private javax.swing.JTextField inputansetor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton keluar1;
    private javax.swing.JLabel nilai;
    private javax.swing.JButton oktarik;
    private javax.swing.JTextField penarikan;
    private javax.swing.JButton ya;
    // End of variables declaration//GEN-END:variables
}
