/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Frame2 extends javax.swing.JFrame {
        String str, str1;
        int choice,z,pin=1234,counter=0,a=3;
        int t,s,tab=50000;

    /**
     * Creates new form Frame2
     */
    public Frame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        info = new javax.swing.JButton();
        penyetoran = new javax.swing.JButton();
        petunjuk = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        penarikan1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        jLabel2.setText("BNI SYARIAH CABANG NGAWI");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 10, 340, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Jln. Yos Sudarso No.17 B, Kec.Ngawi, Kab. Ngawi, Jawa Timur");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 30, 380, 20);

        jLabel1.setFont(new java.awt.Font("Century751 No2 BT", 2, 14)); // NOI18N
        jLabel1.setText("BNI Syariah Memberikan Yang Terbaik Sesuai Kaidah");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 80, 350, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Silahkan Pilih Layanan Yang Anda Inginkan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 100, 280, 30);

        keluar.setBackground(new java.awt.Color(255, 0, 204));
        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(310, 400, 170, 30);

        info.setBackground(new java.awt.Color(102, 255, 102));
        info.setText("INFORMASI SALDO");
        info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoActionPerformed(evt);
            }
        });
        getContentPane().add(info);
        info.setBounds(20, 160, 170, 30);

        penyetoran.setBackground(new java.awt.Color(153, 153, 255));
        penyetoran.setText("PENYETORAN");
        penyetoran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penyetoranActionPerformed(evt);
            }
        });
        getContentPane().add(penyetoran);
        penyetoran.setBounds(20, 280, 170, 30);

        petunjuk.setBackground(new java.awt.Color(153, 255, 255));
        petunjuk.setText("PETUNJUK");
        petunjuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petunjukActionPerformed(evt);
            }
        });
        getContentPane().add(petunjuk);
        petunjuk.setBounds(20, 340, 170, 30);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 12)); // NOI18N
        jLabel5.setText("<html> Jika Anda ingin mengetahui besar saldo yang anda miliki, cukup tekan button ini </html>");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 10, 270, 30);

        jPanel5.setBackground(new java.awt.Color(0, 255, 102));
        jPanel5.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 12)); // NOI18N
        jLabel9.setText("<html> Jika Anda ingin mengetahui besar saldo yang anda miliki, cukup tekan button ini </html>");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(20, 10, 270, 30);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(180, 120, 60, 70);

        jPanel8.setBackground(new java.awt.Color(204, 255, 204));
        jPanel8.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 12)); // NOI18N
        jLabel12.setText("<html> Jika Anda ingin mengetahui besar saldo yang anda miliki, cukup tekan button ini </html>");
        jPanel8.add(jLabel12);
        jLabel12.setBounds(20, 10, 270, 30);

        jPanel9.setBackground(new java.awt.Color(0, 255, 102));
        jPanel9.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 12)); // NOI18N
        jLabel13.setText("<html> Jika Anda ingin mengetahui besar saldo yang anda miliki, cukup tekan button ini </html>");
        jPanel9.add(jLabel13);
        jLabel13.setBounds(20, 10, 270, 30);

        jPanel8.add(jPanel9);
        jPanel9.setBounds(180, 120, 60, 70);

        jPanel1.add(jPanel8);
        jPanel8.setBounds(180, 150, 280, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(180, 150, 280, 50);

        penarikan1.setBackground(new java.awt.Color(255, 153, 153));
        penarikan1.setText("PENARIKAN ");
        penarikan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penarikan1ActionPerformed(evt);
            }
        });
        getContentPane().add(penarikan1);
        penarikan1.setBounds(20, 220, 170, 30);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 12)); // NOI18N
        jLabel6.setText("<html> Jika Anda ingin melakukan penarikan tunai, cukup tekan button ini </html>");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 10, 270, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(180, 210, 280, 50);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 12)); // NOI18N
        jLabel8.setText("<html> Jika Anda ingin melakukan penyetoran untuk menambah saldo Anda, cukup tekan button ini </html>");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(20, 0, 270, 50);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(180, 270, 280, 50);

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 12)); // NOI18N
        jLabel10.setText("<html> Jika Anda ingin melakukan penyetoran untuk menambah saldo Anda, cukup tekan button ini </html>");
        jPanel6.add(jLabel10);
        jLabel10.setBounds(20, 0, 270, 50);

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));
        jPanel7.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 12)); // NOI18N
        jLabel11.setText("<html> Jika Anda ingin melakukan penyetoran untuk menambah saldo Anda, cukup tekan button ini </html>");
        jPanel7.add(jLabel11);
        jLabel11.setBounds(20, 0, 270, 50);

        jPanel6.add(jPanel7);
        jPanel7.setBounds(180, 270, 280, 50);

        jPanel3.add(jPanel6);
        jPanel6.setBounds(180, 270, 280, 50);

        jLabel14.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 12)); // NOI18N
        jLabel14.setText("<html> Jika Anda ingin melakukan penyetoran untuk menambah saldo Anda, cukup tekan button ini </html>");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(20, 0, 270, 50);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(180, 270, 280, 50);

        jPanel10.setBackground(new java.awt.Color(204, 255, 255));
        jPanel10.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 12)); // NOI18N
        jLabel7.setText("<html> Jika Anda kebingungan menggunakan program ini, cukup tekan button ini </html>");
        jPanel10.add(jLabel7);
        jLabel7.setBounds(20, 0, 270, 50);

        getContentPane().add(jPanel10);
        jPanel10.setBounds(180, 330, 280, 50);

        setBounds(0, 0, 514, 481);
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
         new Framee1().setVisible(true);   
         dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    private void infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoActionPerformed
        new Frame4().setVisible(true);   
        dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_infoActionPerformed

    private void penyetoranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penyetoranActionPerformed
        new Frame6().setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_penyetoranActionPerformed

    private void petunjukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petunjukActionPerformed
        new Frame7().setVisible(true); 
        dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_petunjukActionPerformed

    private void penarikan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penarikan1ActionPerformed
        new Frame6().setVisible(true);
        dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_penarikan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton keluar;
    private javax.swing.JButton penarikan1;
    private javax.swing.JButton penyetoran;
    private javax.swing.JButton petunjuk;
    // End of variables declaration//GEN-END:variables
}
